language: elixir
sudo: false
elixir: 1.6.1
otp_release: 20.1
cache:
  directories:
    - deps
    - _build
env:
  - COWBOY_VERSION=1.0
  - COWBOY_VERSION=2.0
script:
  - mix format --check-formatted
  - mix coveralls.travis
after_script:
  - MIX_ENV=test mix inch.report
