language: elixir

sudo: false

cache:
  directories:
    - deps
    - _build

matrix:
  include:
    - otp_release: 19.0
      elixir: 1.6.0
    - otp_release: 20.0
      elixir: 1.6.1
    - otp_release: 21.0
      elixir: 1.6.6

script: mix coveralls.travis

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
